// Generated by kea-typegen on Tue, 25 Jul 2023 23:24:27 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { PieceType } from './pieces'

export interface coreLogicType extends Logic {
    actionCreators: {
        setCategory: (category: string) => ({
            type: "set category (...src.coreLogic)";
            payload: {
                category: string;
            };
        });
    };
    actionKeys: {
        "set category (...src.coreLogic)": "setCategory";
    };
    actionTypes: {
        setCategory: "set category (...src.coreLogic)";
    };
    actions: {
        setCategory: (category: string) => void;
    };
    asyncActions: {
        setCategory: (category: string) => Promise<any>;
    };
    defaults: {
        currentCategory: string;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "",
        "",
        "",
        "src",
        "coreLogic"
    ];
    pathString: "...src.coreLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        currentCategory: string;
    };
    reducers: {
        currentCategory: (state: string, action: any, fullState: any) => string;
    };
    selector: (state: any) => {
        currentCategory: string;
    };
    selectors: {
        currentCategory: (state: any, props?: any) => string;
        filteredPieces: (state: any, props?: any) => PieceType[];
    };
    sharedListeners: {};
    values: {
        currentCategory: string;
        filteredPieces: PieceType[];
    };
    _isKea: true;
    _isKeaWithKey: false;
    __keaTypeGenInternalSelectorTypes: {
        filteredPieces: (currentCategory: string) => PieceType[];
    };
}